apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: aasolovey/hipster-paymentservice:v0.0.2
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"